# Settings for Archives Parlementaires

# log_dir:  directory for log file  (default logs, relative to harvestdor gem path)
log_dir: logs/ap  
# log_name: name of log file  (default: harvestdor.log)
log_name: ap.stage.20130423.fix-session-titles-rethree

# purl: url for the DOR purl server (used to get ContentMetadata, etc.)
purl: http://purl.stanford.edu
# stacks: base url for the digital stacks (no trailing slash)
stacks: https://stacks.stanford.edu

# ---------- White and Black list parameters -----

# name of file containing druids that will NOT be profiled even if they are harvested via OAI
#  either give absolute directory, or directory relative to where the command will be executed
#blacklist: config/ap_blacklist.txt

# name of file containing druids that WILL be profiled (all others will be ignored)
#  either give absolute directory, or directory relative to where the command will be executed
whitelist: config/ap_whitelist.txt
#whitelist: config/ap-druids.batch2

# ----------- SOLR index (that we're writing INTO) parameters ------------
solr:
  url: https://sul-solr.stanford.edu/solr/frda-stage
  # timeouts are in seconds;  read_timeout -> open/read, open_timeout -> connection open
  read_timeout: 90
  open_timeout: 90

# ---------- OAI harvesting parameters -----------

# oai_repository_url:  URL of the OAI data provider
oai_repository_url: https://dor-oaiprovider-prod.stanford.edu/oai

# default_set:  default set for harvest  (default: nil)
#   can be overridden on calls to harvest_ids and harvest_records
default_set: is_governed_by_hy787xj5878

# default_metadata_prefix:  default metadata prefix to be used for harvesting  (default: mods)
#   can be overridden on calls to harvest_ids and harvest_records

# default_from_date:  default from date for harvest  (default: nil)
#   can be overridden on calls to harvest_ids and harvest_records

# default_until_date:  default until date for harvest  (default: nil)
#   can be overridden on calls to harvest_ids and harvest_records

# oai_client_debug:  true for OAI::Client debug mode  (default: false)

# Additional options to pass to Faraday http client (https://github.com/technoweenie/faraday)
http_options:
  ssl:
    verify: false
  # timeouts are in seconds;  timeout -> open/read, open_timeout -> connection open
  timeout: 180
  open_timeout: 180

